name: Run dbt build and test on push

on:
  workflow_dispatch:

env:
  DBT_PROFILES_DIR: .
  DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_TOKEN }}

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dbt-deps
        uses: mwhitaker/dbt-action@fishtown-v0.19.1
        with:
          dbt_command: |
           "dbt deps"
           "dbt run"
           "dbt test"
          dbt_project_folder: "dbt_project"