name: Multiline

on:
  push:
    branches:
      - 'main'  # Runs on push to 'main' branch

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt for SQL Server
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-mssql

      - name: Verify dbt Installation
        run: dbt --version

      - name: Setup dbt Profile for SQL Server
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.PROFILES_YML }}" > ~/.dbt/profiles.yml
          echo "profiles.yml configured for SQL Server"

      - name: dbt-deps
        uses: mwhitaker/dbt-action@v1.6.3
        with:
          dbt_command: "dbt deps && dbt run && dbt test"
          dbt_project_folder: "dbt_project"
